spring:
  data:
    jdbc:
      repositories:
        enabled: true
    jpa:
      repositories:
        bootstrap-mode: default
        enabled: true
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    show-sql: false

coffee-shop:
  promotion:
    free-espresso-for-lattes:
      num-lattes: 2
    latte-price-for-total-amount:
      total-amount: 50 USD
      latte-price: 3 USD
    total-discount-for-products:
      num-products: 8
      total-discount: 0.05
